// Regarding key, see note at the end 
const lstCountries = [
    {key: "XW", name: "Worldwide", nameEs: "Mundial"},
    {key: "AF", name: "Afghanistan", nameEs: "Afganistán"},
    {key: "AL", name: "Albania", nameEs: "Albania"},
    {key: "DZ", name: "Algeria", nameEs: "Algeria"},
    {key: "AS", name: "American Samoa", nameEs: "Samoa Americana"},
    {key: "AD", name: "Andorra", nameEs: "Andorra"},
    {key: "AO", name: "Angola", nameEs: "Angola"},
    {key: "AI", name: "Anguilla", nameEs: "Anguila"},
    {key: "AQ", name: "Antarctica", nameEs: "Antártida"},
    {key: "AG", name: "Antigua And Barbuda", nameEs: "Antigua y Barbuda"},
    {key: "AR", name: "Argentina", nameEs: "Argentina"},
    {key: "AM", name: "Armenia", nameEs: "Armenia"},
    {key: "AW", name: "Aruba", nameEs: "Aruba"},
    {key: "AU", name: "Australia", nameEs: "Australia"},
    {key: "AT", name: "Austria", nameEs: "Austria"},
    {key: "AZ", name: "Azerbaijan", nameEs: "Azerbaiyán"},
    {key: "BS", name: "Bahamas", nameEs: "Bahamas"},
    {key: "BH", name: "Bahrain", nameEs: "Baréin"},
    {key: "BD", name: "Bangladesh", nameEs: "Bangladesh"},
    {key: "BB", name: "Barbados", nameEs: "Barbados"},
    {key: "BY", name: "Belarus", nameEs: "Bielorrusia"},
    {key: "BE", name: "Belgium", nameEs: "Belgica"},
    {key: "BZ", name: "Belize", nameEs: "Belice"},
    {key: "BJ", name: "Benin", nameEs: "Benín"},
    {key: "BM", name: "Bermuda", nameEs: "Bermuda"},
    {key: "BT", name: "Bhutan", nameEs: "Bután"},
    {key: "BO", name: "Bolivia", nameEs: "Bolivia"},
    {key: "BA", name: "Bosnia And Herzegowina", nameEs: "Bosnia y Herzegovina"},
    {key: "BW", name: "Botswana", nameEs: "Botswana"},
    {key: "BV", name: "Bouvet Island", nameEs: "Isla Bouvet"},
    {key: "BR", name: "Brazil", nameEs: "Brasil"},
    {key: "IO", name: "British Indian Ocean Territory", nameEs: "British Indian Ocean Territory"},
    {key: "BN", name: "Brunei Darussalam", nameEs: "Brunéi"},
    {key: "BG", name: "Bulgaria", nameEs: "Bulgaria"},
    {key: "BF", name: "Burkina Faso", nameEs: "Burkina Faso"},
    {key: "BI", name: "Burundi", nameEs: "Burundi"},
    {key: "KH", name: "Cambodia", nameEs: "Camboya"},
    {key: "CM", name: "Cameroon", nameEs: "Camerún"},
    {key: "CA", name: "Canada", nameEs: "Canadá"},
    {key: "CV", name: "Cape Verde", nameEs: "Cabo Verde"},
    {key: "KY", name: "Cayman Islands", nameEs: "Islas Caimán"},
    {key: "CF", name: "Central African Republic", nameEs: "Republica Centroafricana"},
    {key: "TD", name: "Chad", nameEs: "Chad"},
    {key: "CL", name: "Chile", nameEs: "Chile"},
    {key: "CN", name: "China", nameEs: "China"},
    {key: "CX", name: "Christmas Island", nameEs: "Isla Navidad"},
    {key: "CC", name: "Cocos (Keeling) Islands", nameEs: "Isla del Coco"},
    {key: "CO", name: "Colombia", nameEs: "Colombia"},
    {key: "KM", name: "Comoros", nameEs: "Comoras"},
    {key: "CG", name: "Congo", nameEs: "Congo"},
    {key: "CK", name: "Cook Islands", nameEs: "Islas Cook"},
    {key: "CR", name: "Costa Rica", nameEs: "Costa Rica"},
    {key: "CI", name: "Cote D'Ivoire", nameEs: "Costa de Marfil"},
    {key: "HR", name: "Croatia (Local Name: Hrvatska)", nameEs: "Croacia"},
    {key: "CU", name: "Cuba", nameEs: "Cuba"},
    {key: "CY", name: "Cyprus", nameEs: "Chipre"},
    {key: "CZ", name: "Czech Republic", nameEs: "Republica Checa"},
    {key: "DK", name: "Denmark", nameEs: "Dinamarca"},
    {key: "DJ", name: "Djibouti", nameEs: "Yibuti"},
    {key: "DM", name: "Dominica", nameEs: "Dominica"},
    {key: "DO", name: "Dominican Republic", nameEs: "Republica Dominicana"},
    {key: "TP", name: "East Timor", nameEs: "Timor Oriental"},
    {key: "EC", name: "Ecuador", nameEs: "Ecuador"},
    {key: "EG", name: "Egypt", nameEs: "Egipto"},
    {key: "SV", name: "El Salvador", nameEs: "El Salvador"},
    {key: "GQ", name: "Equatorial Guinea", nameEs: "Guinea Ecuatorial"},
    {key: "ER", name: "Eritrea", nameEs: "Eritrea"},
    {key: "EE", name: "Estonia", nameEs: "Estonia"},
    {key: "ET", name: "Ethiopia", nameEs: "Etiopía"},
    {key: "FK", name: "Falkland Islands (Malvinas)", nameEs: "Islands Malvinas"},
    {key: "FO", name: "Faroe Islands", nameEs: "Islas Faroe"},
    {key: "FJ", name: "Fiji", nameEs: "Fiyi"},
    {key: "FI", name: "Finland", nameEs: "Finlandia"},
    {key: "FR", name: "France", nameEs: "Francia"},
    {key: "GF", name: "French Guiana", nameEs: "Guayana Francesa"},
    {key: "PF", name: "French Polynesia", nameEs: "Polinesia Francesa"},
    {key: "TF", name: "French Southern Territories", nameEs: "French Southern Territories"},
    {key: "GA", name: "Gabon", nameEs: "Gabón"},
    {key: "GM", name: "Gambia", nameEs: "Gambia"},
    {key: "GE", name: "Georgia", nameEs: "Georgia"},
    {key: "DE", name: "Germany", nameEs: "Alemania"},
    {key: "GH", name: "Ghana", nameEs: "Ghana"},
    {key: "GI", name: "Gibraltar", nameEs: "Gibraltar"},
    {key: "GR", name: "Greece", nameEs: "Grecia"},
    {key: "GL", name: "Greenland", nameEs: "Groenlandia"},
    {key: "GD", name: "Grenada", nameEs: "Granada"},
    {key: "GP", name: "Guadeloupe", nameEs: "Guadelupe"},
    {key: "GU", name: "Guam", nameEs: "Guam"},
    {key: "GT", name: "Guatemala", nameEs: "Guatemala"},
    {key: "GN", name: "Guinea", nameEs: "Guinea"},
    {key: "GW", name: "Guinea-Bissau", nameEs: "Guinea-Bissau"},
    {key: "GY", name: "Guyana", nameEs: "Guyana"},
    {key: "HT", name: "Haiti", nameEs: "Haití"},
    {key: "HM", name: "Heard And Mc Donald Islands", nameEs: "Islas Heard y McDonald"},
    {key: "VA", name: "Holy See (Vatican City State)", nameEs: "El Vaticano"},
    {key: "HN", name: "Honduras", nameEs: "Honduras"},
    {key: "HK", name: "Hong Kong", nameEs: "Hong Kong"},
    {key: "HU", name: "Hungary", nameEs: "Hungría"},
    {key: "IS", name: "Icel And", nameEs: "Islandia"},
    {key: "IN", name: "India", nameEs: "India"},
    {key: "ID", name: "Indonesia", nameEs: "Indonesia"},
    {key: "IR", name: "Iran (Islamic Republic Of)", nameEs: "Irán"},
    {key: "IQ", name: "Iraq", nameEs: "Iraq"},
    {key: "IE", name: "Ireland", nameEs: "Irlanda"},
    {key: "IL", name: "Israel", nameEs: "Israel"},
    {key: "IT", name: "Italy", nameEs: "Italia"},
    {key: "JM", name: "Jamaica", nameEs: "Jamaica"},
    {key: "JP", name: "Japan", nameEs: "Japón"},
    {key: "JO", name: "Jordan", nameEs: "Jordania"},
    {key: "KZ", name: "Kazakhstan", nameEs: "Kazajistán"},
    {key: "KE", name: "Kenya", nameEs: "Kenia"},
    {key: "KI", name: "Kiribati", nameEs: "Kiribati"},
    {key: "KP", name: "Korea, Dem People'S Republic", nameEs: "Korea del Norte"},
    {key: "KR", name: "Korea, Republic Of", nameEs: "Korea del Sur"},
    {key: "KW", name: "Kuwait", nameEs: "Kuwait"},
    {key: "KG", name: "Kyrgyzstan", nameEs: "Kirguistán"},
    {key: "LA", name: "Lao People'S Dem Republic", nameEs: "Laos"},
    {key: "LV", name: "Latvia", nameEs: "Letonia"},
    {key: "LB", name: "Lebanon", nameEs: "Líbano"},
    {key: "LS", name: "Lesotho", nameEs: "Lesoto"},
    {key: "LR", name: "Liberia", nameEs: "Liberia"},
    {key: "LY", name: "Libyan Arab Jamahiriya", nameEs: "Libia"},
    {key: "LI", name: "Liechtenstein", nameEs: "Liechtenstein"},
    {key: "LT", name: "Lithuania", nameEs: "Lituania"},
    {key: "LU", name: "Luxembourg", nameEs: "Luxemburgo"},
    {key: "MO", name: "Macau", nameEs: "Macao"},
    {key: "MK", name: "Macedonia", nameEs: "Macedonia"},
    {key: "MG", name: "Madagascar", nameEs: "Madagascar"},
    {key: "MW", name: "Malawi", nameEs: "Malawi"},
    {key: "MY", name: "Malaysia", nameEs: "Malasia"},
    {key: "MV", name: "Maldives", nameEs: "Maldivas"},
    {key: "ML", name: "Mali", nameEs: "Mali"},
    {key: "MT", name: "Malta", nameEs: "Malta"},
    {key: "MH", name: "Marshall Islands", nameEs: "Islas Marshall"},
    {key: "MQ", name: "Martinique", nameEs: "Martinica"},
    {key: "MR", name: "Mauritania", nameEs: "Mauritania"},
    {key: "MU", name: "Mauritius", nameEs: "Mauricio"},
    {key: "YT", name: "Mayotte", nameEs: "Mayotte"},
    {key: "MX", name: "Mexico", nameEs: "México"},
    {key: "FM", name: "Micronesia, Federated States", nameEs: "Micronesia"},
    {key: "MD", name: "Moldova, Republic Of", nameEs: "Moldovia"},
    {key: "MC", name: "Monaco", nameEs: "Mónaco"},
    {key: "MN", name: "Mongolia", nameEs: "Mongolia"},
    {key: "MS", name: "Montserrat", nameEs: "Montserrat"},
    {key: "MA", name: "Morocco", nameEs: "Marruecos"},
    {key: "MZ", name: "Mozambique", nameEs: "Mozambique"},
    {key: "MM", name: "Myanmar", nameEs: "Birmania"},
    {key: "NA", name: "Namibia", nameEs: "Namibia"},
    {key: "NR", name: "Nauru", nameEs: "Nauru"},
    {key: "NP", name: "Nepal", nameEs: "Nepal"},
    {key: "NL", name: "Netherlands", nameEs: "Países Bajos"},
    {key: "AN", name: "Netherlands Ant Illes", nameEs: "Antillas Neerlandesas"},
    {key: "NC", name: "New Caledonia", nameEs: "Nueva Caledonia"},
    {key: "NZ", name: "New Zealand", nameEs: "Nueva Zelanda"},
    {key: "NI", name: "Nicaragua", nameEs: "Nicaragua"},
    {key: "NE", name: "Niger", nameEs: "Níger"},
    {key: "NG", name: "Nigeria", nameEs: "Nigeria"},
    {key: "NU", name: "Niue", nameEs: "Niue"},
    {key: "NF", name: "Norfolk Island", nameEs: "Isla Norfolk"},
    {key: "MP", name: "Northern Mariana Islands", nameEs: "Islas Marianas del Norte"},
    {key: "NO", name: "Norway", nameEs: "Noruega"},
    {key: "OM", name: "Oman", nameEs: "Omán"},
    {key: "PK", name: "Pakistan", nameEs: "Pakistán"},
    {key: "PW", name: "Palau", nameEs: "Palaos"},
    {key: "PA", name: "Panama", nameEs: "Panamá"},
    {key: "PG", name: "Papua New Guinea", nameEs: "Papua Nueva Guinea"},
    {key: "PY", name: "Paraguay", nameEs: "Paraguay"},
    {key: "PE", name: "Peru", nameEs: "Perú"},
    {key: "PH", name: "Philippines", nameEs: "Filipinas"},
    {key: "PN", name: "Pitcairn", nameEs: "Pitcairn"},
    {key: "PL", name: "Poland", nameEs: "Polonia"},
    {key: "PT", name: "Portugal", nameEs: "Portugal"},
    {key: "PR", name: "Puerto Rico", nameEs: "Puerto Rico"},
    {key: "QA", name: "Qatar", nameEs: "Catar"},
    {key: "RE", name: "Reunion", nameEs: "Reunión"},
    {key: "RO", name: "Romania", nameEs: "Rumania"},
    {key: "RU", name: "Russian Federation", nameEs: "Rusia"},
    {key: "RW", name: "Rwanda", nameEs: "Ruanda"},
    {key: "KN", name: "Saint K Itts And Nevis", nameEs: "San Cristóbal y Nieves"},
    {key: "LC", name: "Saint Lucia", nameEs: "Santa Lucía"},
    {key: "VC", name: "Saint Vincent, The Grenadines", nameEs: "San Vicente y las Granadinas"},
    {key: "WS", name: "Samoa", nameEs: "Samoa"},
    {key: "SM", name: "San Marino", nameEs: "San Marino"},
    {key: "ST", name: "Sao Tome And Principe", nameEs: "Santo Tomé y Príncipe"},
    {key: "SA", name: "Saudi Arabia", nameEs: "Arabia Saudita"},
    {key: "SN", name: "Senegal", nameEs: "Senegal"},
    {key: "SC", name: "Seychelles", nameEs: "Seychelles"},
    {key: "SL", name: "Sierra Leone", nameEs: "Sierra Leona"},
    {key: "SG", name: "Singapore", nameEs: "Singapur"},
    {key: "SK", name: "Slovakia (Slovak Republic)", nameEs: "Eslovaquia"},
    {key: "SI", name: "Slovenia", nameEs: "Eslovenia"},
    {key: "SB", name: "Solomon Islands", nameEs: "Islas Salomón"},
    {key: "SO", name: "Somalia", nameEs: "Somalia"},
    {key: "ZA", name: "South Africa", nameEs: "Sudáfrica"},
    {key: "GS", name: "South Georgia , S Sandwich Is.", nameEs: "Islas Georgias del Sur y Sandwich del Sur"},
    {key: "ES", name: "Spain", nameEs: "España"},
    {key: "LK", name: "Sri Lanka", nameEs: "Sri Lanka"},
    {key: "SH", name: "St. Helena", nameEs: "Santa Elena"},
    {key: "PM", name: "St. Pierre And Miquelon", nameEs: "San Pedro y Miquelón"},
    {key: "SD", name: "Sudan", nameEs: "Sudán"},
    {key: "SR", name: "Suriname", nameEs: "Surinam"},
    {key: "SJ", name: "Svalbard, Jan Mayen Islands", nameEs: "Svalbard y Jan Mayen"},
    {key: "SZ", name: "Sw Aziland", nameEs: "Sw Aziland"},
    {key: "SE", name: "Sweden", nameEs: "Suecia"},
    {key: "CH", name: "Switzerland", nameEs: "Suiza"},
    {key: "SY", name: "Syrian Arab Republic", nameEs: "Siria"},
    {key: "TW", name: "Taiwan", nameEs: "Taiwán"},
    {key: "TJ", name: "Tajikistan", nameEs: "Tayikistán"},
    {key: "TZ", name: "Tanzania, United Republic Of", nameEs: "Tanzania"},
    {key: "TH", name: "Thailand", nameEs: "Tailandia"},
    {key: "TG", name: "Togo", nameEs: "Togo"},
    {key: "TK", name: "Tokelau", nameEs: "Tokelau"},
    {key: "TO", name: "Tonga", nameEs: "Tonga"},
    {key: "TT", name: "Trinidad And Tobago", nameEs: "Trinidad y Tobago"},
    {key: "TN", name: "Tunisia", nameEs: "Túnez"},
    {key: "TR", name: "Turkey", nameEs: "Turquía"},
    {key: "TM", name: "Turkmenistan", nameEs: "Turkmenistán"},
    {key: "TC", name: "Turks And Caicos Islands", nameEs: "Islas Turcas y Caicos"},
    {key: "TV", name: "Tuvalu", nameEs: "Tuvalu"},
    {key: "UG", name: "Uganda", nameEs: "Uganda"},
    {key: "UA", name: "Ukraine", nameEs: "Ucrania"},
    {key: "AE", name: "United Arab Emirates", nameEs: "Emiratos Unidos Árabes"},
    {key: "GB", name: "United Kingdom", nameEs: "Reino Unido"},
    {key: "US", name: "United States", nameEs: "Estados Unidos"},
    {key: "UM", name: "United States Minor Is.", nameEs: "Islas Ultramarinas Menores de Estados Unidos"},
    {key: "UY", name: "Uruguay", nameEs: "Uruguay"},
    {key: "UZ", name: "Uzbekistan", nameEs: "Uzbekistán"},
    {key: "VU", name: "Vanuatu", nameEs: "Vanuatu"},
    {key: "VE", name: "Venezuela", nameEs: "Venezuela"},
    {key: "VN", name: "Viet Nam", nameEs: "Vietnam"},
    {key: "VG", name: "Virgin Islands (British)", nameEs: "Islas Británicas Vírgenes)"},
    {key: "VI", name: "Virgin Islands (U.S.)", nameEs: "Islas Vírgenes de los Estados Unidos"},
    {key: "WF", name: "Wallis And Futuna Islands", nameEs: "Wallis y Futuna"},
    {key: "EH", name: "Western Sahara", nameEs: "Sahara Occidental"},
    {key: "YE", name: "Yemen", nameEs: "Yemen"},
    {key: "ZR", name: "Zaire", nameEs: "Zaire"},
    {key: "ZM", name: "Zambia", nameEs: "Zambia"},
    {key: "ZW", name: "Zimbabwe", nameEs: "Zimbabue"}
    ];

export default lstCountries;

// For the abbreviation of the countries would be fantastic using the key as a descriptive word
// rather than key. However, for a reason, when key is used is use to define the key in some 
// list, it does not work.